export const APP_NAME = "AmorPOS";
export const BAKERY_NAME = "Panadería Amores";

export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  POS: "/pos",
  INVENTORY: "/inventory",
  PRODUCTS: "/products",
  RAW_MATERIALS: "/raw-materials",
  RECIPES: "/recipes",
  SUPPLIERS: "/suppliers",
  REPORTS: "/reports",
  BRANCHES: "/branches",
  USERS: "/users",
};

export const UI_TEXT = {
  LOGIN_TITLE: "Iniciar Sesión",
  LOGIN_BUTTON: "Ingresar",
  LOGOUT_BUTTON: "Cerrar Sesión",
  USERNAME_LABEL: "Usuario",
  PASSWORD_LABEL: "Contraseña",
  BRANCH_LABEL: "Sucursal",
  POS_TITLE: "Punto de Venta",
  INVENTORY_TITLE: "Inventario General",
  PRODUCTS_TITLE: "Productos",
  RAW_MATERIALS_TITLE: "Materia Prima",
  RECIPES_TITLE: "Recetas",
  SUPPLIERS_TITLE: "Proveedores",
  REPORTS_TITLE: "Reportes de Ventas",
  BRANCHES_TITLE: "Sucursales",
  USERS_TITLE: "Usuarios",
  LOADING: "Cargando...",
  WELCOME_MESSAGE: `Bienvenido a ${APP_NAME}`,
  NAVIGATION: "Navegación",
  ADD_TO_CART: "Agregar",
  CART_TITLE: "Carrito",
  TOTAL: "Total",
  CHECKOUT: "Cobrar",
  CLEAR_CART: "Vaciar Carrito",
  ITEM_NAME: "Nombre",
  STOCK: "Existencia",
  UNIT: "Unidad",
  ACTIONS: "Acciones",
  UPDATE_STOCK: "Actualizar",
  MIN_STOCK: "Stock Mínimo",
  SALES_DATA_LABEL: "Datos de Ventas (JSON)",
  SALES_DATA_PLACEHOLDER: `{
  "ventas": [
    {"item": "Concha de Vainilla", "cantidadVendida": 50},
    {"item": "Bolillo", "cantidadVendida": 120}
  ],
  "inventarioActual": [
    {"item": "Concha de Vainilla", "stock": 20},
    {"item": "Bolillo", "stock": 10}
  ]
}`,
  ANALYZE_SALES: "Analizar Ventas",
  ANALYSIS_RESULTS: "Resultados del Análisis",
  ITEMS_TO_ADJUST: "Artículos para Ajustar Inventario",
  REASONING: "Justificación",
  NO_DATA: "No hay datos para mostrar.",
  NO_ITEMS_IN_CART: "El carrito está vacío.",
  TRANSACTION_SUCCESS: "Transacción completada.",
  ERROR_LOGIN_FAILED: "Usuario o contraseña incorrectos.",
  ERROR_ANALYSIS: "Error al analizar los datos.",
  PRODUCT_CATEGORIES: {
    PAN_DULCE: "Pan Dulce",
    PAN_SALADO: "Pan Salado",
    PASTELES: "Pasteles",
    BEBIDAS: "Bebidas",
    OTROS: "Otros",
  },
  RAW_MATERIAL_CATEGORIES: {
    INGREDIENTES: "Ingredientes",
    EMPAQUES: "Empaques",
    LIMPIEZA: "Limpieza",
    OTROS: "Otros Insumos",
  },
  PRODUCT_TYPES_LABELS: {
    third_party_sale: "Terceros para Venta",
    third_party_production: "Terceros para Producción",
    produced_item: "Artículo Producido",
  },
  UNITS: {
    UNIDADES: "unidades",
    KG: "kg",
    GR: "gr",
    LITROS: "litros",
    ML: "ml",
    CAJA: "caja",
    PAQUETE: "paquete",
  },
  VIEW_DETAILS: "Ver detalles",
  INVENTORY_ADVICE: "Consejos de Inventario por IA",
  SALES_REPORT_DESCRIPTION: "Ingrese los datos de ventas en formato JSON para obtener un análisis y recomendaciones de inventario.",
  
  ADD_BRANCH: "Agregar Sucursal",
  EDIT_BRANCH: "Editar Sucursal",
  DELETE_BRANCH: "Eliminar Sucursal",
  BRANCH_NAME: "Nombre de Sucursal",
  ADDRESS: "Dirección",
  PHONE: "Teléfono",
  
  ADD_USER: "Agregar Usuario",
  EDIT_USER: "Editar Usuario",
  DELETE_USER: "Eliminar Usuario",
  IDENTIFICATION: "Identificación",
  USERNAME: "Nombre de Usuario",
  FIRST_NAME: "Nombres",
  LAST_NAME: "Apellidos",
  STATUS: "Estado",
  ROLES: "Roles",
  IS_BLOCKED: "Bloqueado",
  ASSIGN_ROLES: "Asignar Roles",
  USER_STATE_BLOCKED: "Bloqueado",
  USER_STATE_ACTIVE: "Activo",
  
  SAVE_CHANGES: "Guardar Cambios",
  CANCEL: "Cancelar",
  ARE_YOU_SURE: "¿Está seguro?",
  DELETE_CONFIRM_MESSAGE: "Esta acción no se puede deshacer.",
  DELETE: "Eliminar",

  MANAGE_BRANCHES_DESCRIPTION: "Administre las sucursales de la panadería.",
  MANAGE_USERS_DESCRIPTION: "Administre los usuarios del sistema y sus roles.",
  MANAGE_PRODUCTS_DESCRIPTION: "Defina y administre los productos de la panadería.",
  MANAGE_RAW_MATERIALS_DESCRIPTION: "Administre la materia prima y otros insumos.",
  MANAGE_RECIPES_DESCRIPTION: "Cree y administre las recetas para los productos elaborados.",
  MANAGE_SUPPLIERS_DESCRIPTION: "Administre la información de los proveedores.",

  PRODUCT_TYPE: "Tipo de Producto",
  CATEGORY: "Categoría",
  PRICE: "Precio Venta",
  COST: "Costo",
  SUPPLIER: "Proveedor",
  RECIPE: "Receta",
  DESCRIPTION: "Descripción",
  ADD_PRODUCT: "Agregar Producto",
  EDIT_PRODUCT: "Editar Producto",
  
  ADD_RAW_MATERIAL: "Agregar Materia Prima",
  EDIT_RAW_MATERIAL: "Editar Materia Prima",
  MIN_QUANTITY_TOLERANCE: "Cant. Tolerancia Mínima",

  ADD_SUPPLIER: "Agregar Proveedor",
  EDIT_SUPPLIER: "Editar Proveedor",
  EMAIL: "Correo Electrónico",
  CONTACT_PERSON: "Persona de Contacto",
  
  ADD_RECIPE: "Crear Receta",
  EDIT_RECIPE: "Editar Receta",
  RECIPE_NAME: "Nombre de la Receta",
  PRODUCES_PRODUCT: "Producto Elaborado",
  YIELD_QUANTITY: "Cantidad Producida",
  YIELD_UNIT: "Unidad Producida",
  INGREDIENTS: "Ingredientes",
  INSTRUCTIONS: "Instrucciones",
  PREPARATION_TIME: "Tiempo de Prep. (min)",
  COOKING_TIME: "Tiempo de Cocción (min)",
  ADD_INGREDIENT: "Agregar Ingrediente",
  ITEM_TYPE: "Tipo de Item",
  QUANTITY: "Cantidad",
};

export const ALL_UNITS = Object.values(UI_TEXT.UNITS);
export const ALL_PRODUCT_CATEGORIES = Object.values(UI_TEXT.PRODUCT_CATEGORIES);
export const ALL_RAW_MATERIAL_CATEGORIES = Object.values(UI_TEXT.RAW_MATERIAL_CATEGORIES);
